CREATE TABLE IF NOT EXISTS water_db (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ounces DECIMAL(5,2) NOT NULL,
    logged_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    log_date DATE DEFAULT CURRENT_DATE
);

CREATE TABLE IF NOT EXISTS daily_goals (
    id INT AUTO_INCREMENT PRIMARY KEY,
    goal_date DATE NOT NULL UNIQUE,
    goal_ounces DECIMAL(5,2) NOT NULL DEFAULT 64.0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);